### ISSUE TITLE
Look into other website partners

### ISSUE THREAD

**Issue by calixo888** [Coronavirus-Visualization-Team/site#41]
@lucas-chu wants to know what websites CVT can partner with. Specifically other orgs with websites similar to CVT, with the same mission in the same field.

**Comment by shreyaganti** [comment]
Here are a few websites and organizations that I found with a similar mission to ours:

- informationisbeautiful.net (has a COVID-19 Coronavirus Infographic Datapack and in general is an organization that hosts seminars on how to conduct data visualizations)

- coronavirus.jhu.edu (database and visualizations based at Johns Hopkins University)

- www.cdc.gov (Data Visualization Page specifically catered to Coronavirus visualizations)

- www.healthmap.org/covid-19/ (Webpage launched by Researchers from the University of Oxford, Harvard Medical School, Boston Children's Hospital and Northeastern University)

- accelerator.weather.com (Webpage by IBM on IBM Cognos Analytics which leverages data from the state and local governments and the WHO. It is designed to be used by researchers, data scientists, and media organizations)

- Tableau (COVID-19 Data Hub. I’m not sure if we are already partnered with the organization for the website specifically, but it is an organization to consider if we haven’t already)

- www.bing.com/covid/ (Microsoft Bing COVID-19 Tracker with statistics aggregated from WHO, CDC, and the European Centre for Disease Prevention and Control (ECDC))

- responselab.stanford.edu (Stanford COVID-19 Response Innovation Lab)

- covidtracking.com (The COVID Tracking Project)
