### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by calixo888** [Coronavirus-Visualization-Team/site#48]
Implement dark mode with theme-ui?

**Comment by calixo888** [comment]
@Jake-Short you'll be picking up where @adway left off in terms of the dark mode feature because he can't continue being website co-lead due to time constraints

**Comment by Jake-Short** [comment]
@calixo888 Sounds good, has the implementation been started in a separate branch?

**Comment by calixo888** [comment]
@Jake-Short So we're waiting on @adway to push his changes first. If he can't or is unable to by tomorrow, you can just start from scratch on a different branch :)

**Comment by Jake-Short** [comment]
OK will do!
