### ISSUE TITLE
Embed new Airtable

### ISSUE THREAD

**Issue by calixo888** [Coronavirus-Visualization-Team/site#51]
Embed this airtable into Resources: http://bit.ly/resourcescovid-19

**Comment by calixo888** [comment]
Use the raw Tableau iFrames from document

**Comment by Jake-Short** [comment]
> Use the raw Tableau iFrames from document

Hey, which document are you referring to? I couldn't find the raw Tableau iFrame.

**Comment by calixo888** [comment]
That's my bad! I made this comment on the wrong issue. Anyways, just embed the entire airtable into the Resources page @Jake-Short
